# Basic
title: 张伟(WeiZhang555)的站点
subtitle: Wei Zhang's website
email: zhangwei_cs@qq.com
description: > # this means to ignore newlines until "baseurl:"
    May the force be with you      
welcome_message: 
creator: <a href="https://weizhang555.github.io">@weizhang555</a>

url: "https://weizhang555.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/WeiZhang555'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: weizhang555
    # duoshuo: 
    
# Social
social:
    github: WeiZhang555
    twitter: WeiZhang555
    # gplus: 107108267983477358170
    mail: zhangwei_cs@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
